apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: ec2-wordpress
spec:
  forProvider:
    ami: ami-023508951a94f0c71 # Amazon Linux 2023 AMI
    associatePublicIpAddress: true
    availabilityZone: us-east-1a
    disableApiStop: false
    disableApiTermination: false
    ebsOptimized: true
    instanceType: t4g.small
    region: us-east-1
    subnetIdSelector:
      matchLabels:
        subnet1: public-az1
    tags:
      Name: ec2-wordpress
      ManagedBy: crossplane
    userData: |
      #!/bin/bash
      # Update the system
      yum update -y
      
      # Install Apache
      yum install -y httpd
      
      # Start and enable Apache
      systemctl start httpd
      systemctl enable httpd
      
      # Install PHP
      amazon-linux-extras enable php8.0
      yum clean metadata
      yum install -y php php-cli php-mysqlnd
      
      # Download and install WordPress
      cd /var/www/html
      wget https://wordpress.org/latest.tar.gz
      tar -xzf latest.tar.gz
      cp -r wordpress/* .
      rm -rf wordpress latest.tar.gz
      
      # Set permissions
      chown -R apache:apache /var/www/html
      chmod -R 755 /var/www/html
      
      # Restart Apache to apply changes
      systemctl restart httpd

    userDataReplaceOnChange: true
    volumeTags:
      Name: ec2-wordpress
      ManagedBy: crossplane
    vpcSecurityGroupIdSelector:
      matchLabels:
        ec2securitygroup: ec2-wordpress-sg

  providerConfigRef:
    name: segoja7
