apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: elbsecuritygroup
  labels:
    elbsecuritygroup: elb-wordpress-sg
spec:
  forProvider:
    description: ELB Wordpress Security Group
    name: elb-wordpress-sg
    region: us-east-1
    revokeRulesOnDelete: true
    tags:
      Name: elb-wordpress-sg
      ManagedBy: crossplane
    vpcIdSelector:
      matchLabels:
        vpc: wordpress
  providerConfigRef:
    name: segoja7
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: world-to-elb-rule
spec:
  forProvider:
    cidrIpv4: 0.0.0.0/0
    description: Allow access to ELB from World
    fromPort: 80
    toPort: 80
    ipProtocol: tcp
    region: us-east-1
    securityGroupIdSelector:
      matchLabels:
        elbsecuritygroup: elb-wordpress-sg
    tags:
      Name: elb-wordpress-sg
      ManagedBy: crossplane
  providerConfigRef:
    name: segoja7
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupEgressRule
metadata:
  name: outbound-rule-elb-wordpress-sg
spec:
  forProvider:
    cidrIpv4: 0.0.0.0/0
    description: Egress Rule
    ipProtocol: "-1"
    region: us-east-1
    securityGroupIdSelector:
      matchLabels:
        elbsecuritygroup: elb-wordpress-sg
    tags:
      Name: elb-wordpress-sg
      ManagedBy: crossplane
  providerConfigRef:
    name: segoja7