apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LB
metadata:
  name: wordpress-elb
  labels:
    elb: wordpress
spec:
  forProvider:
    enableCrossZoneLoadBalancing: true
    enableDeletionProtection: false
    enableHttp2: true
    enableTlsVersionAndCipherSuiteHeaders: false
    idleTimeout: 60
    internal: false
    ipAddressType: ipv4
    loadBalancerType: application
    name: wordpress-elb
    region: us-east-1
    securityGroupSelector:
      matchLabels:
        elbsecuritygroup: elb-wordpress-sg
    subnetRefs:
      - name: public-subnet-az1
      - name: public-subnet-az2
    tags:
      Name: elb-wordpress
      ManagedBy: crossplane
  providerConfigRef:
    name: segoja7
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroup
metadata:
  labels:
    targetgroup: wordpress
  name: wordpress-lb-tg
spec:
  forProvider:
    deregistrationDelay: "300"
    healthCheck:
      - enabled: true
        healthyThreshold: 3
        interval: 30
        path: /
        port: "80"
        protocol: HTTP
        timeout: 3
        unhealthyThreshold: 3
    ipAddressType: ipv4
    loadBalancingCrossZoneEnabled: "true"
    name: wordpress-lb-tg
    port: 80
    protocol: HTTP
    protocolVersion: HTTP1
    region: us-east-1
    tags:
      Name: elb-wordpress
      ManagedBy: crossplane
    targetType: instance
    vpcIdSelector:
      matchLabels:
        vpc: wordpress
  providerConfigRef:
    name: segoja7
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroupAttachment
metadata:
  name: listenertg1-wordpress
spec:
  forProvider:
    port: 80
    region: us-east-1
    targetGroupArnSelector:
      matchLabels:
        targetgroup: wordpress
    targetId: i-0ef6929bbae5ce99c
  providerConfigRef:
    name: segoja7
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBListener
metadata:
  name: listener-wordpress
spec:
  forProvider:
    defaultAction:
      - forward:
          - stickiness:
              - duration: 3600
                enabled: false
#          - targetGroup:
#              - arnSelector:
#                - matchLabels:
#                   - targetgroup: wordpress
      - targetGroupArnSelector:
          matchLabels:
            targetgroup: wordpress
        type: forward
    loadBalancerArnRef:
      name: wordpress-elb
    port: 80
    protocol: HTTP
    region: us-east-1
    tags:
      Name: elb-wordpress
      ManagedBy: crossplane
  providerConfigRef:
    name: segoja7

